#!/usr/bin/env python3
"""Generate src/bitmap_rom.v as a character-indexed font + per-message
character-stream ROM.

Architecture:
  Each bouncer is a 128 x 16 px sprite = 16 chars wide x 16 px tall.
  Per pixel:
    char_x   = lx[6:3]            (which char column, 0..15)
    in_char  = lx[2:0]            (column within glyph, 0..7)
    row      = ly[3:0]            (row within glyph, 0..15)
    char_idx = msg_rom[band, char_x]
    pixel    = font_rom[char_idx, row][in_char]

This shrinks per-bouncer storage from 256 B (16x16 packed pixels) to
16 chars x 5 bits + the shared font (one copy across all 3 ports).
"""

from __future__ import annotations
import gzip
import struct
import subprocess
from pathlib import Path

CHAR_W = 8
CHAR_H = 16
COLS = 16  # 128 / 8
MESSAGES = ["RISC-V Ottawa", "Join us!", "riscvottawa.ca"]

# Use the kernel console PSF2 bitmap font — designed for crisp 8x16 pixel
# rendering, no anti-aliasing, properly baseline-aligned.
PSF_PATH = "/usr/share/kbd/consolefonts/default8x16.psfu.gz"


def collect_chars(msgs: list[str]) -> list[str]:
    """Unique chars used, with space first (so it's index 0 = blank)."""
    used = sorted({c for m in msgs for c in m} | {" "})
    used.remove(" ")
    return [" "] + used


def load_psf_glyphs() -> dict[str, list[int]]:
    """Parse the PSF2 file and return a {char: [16 bytes]} mapping.

    PSF2 layout: 32-byte header, then `length` glyphs of `charsize` bytes
    each, then a Unicode descriptor table that maps glyph index -> code
    point. Each glyph row byte has MSB = leftmost pixel (we re-emit
    LSB-first below to match the Verilog convention).
    """
    with gzip.open(PSF_PATH, "rb") as f:
        data = f.read()
    magic, version, hdr_size, flags, length, charsize, height, width = struct.unpack_from("<IIIIIIII", data, 0)
    assert magic == 0x864AB572, f"bad PSF2 magic {magic:x}"
    assert (height, width, charsize) == (CHAR_H, CHAR_W, CHAR_H), (height, width, charsize)

    glyph_data = data[hdr_size : hdr_size + length * charsize]
    uc_table = data[hdr_size + length * charsize :]

    # Walk the Unicode descriptor table: per glyph, a UTF-8 sequence of
    # code points terminated by 0xFF (sequences and 0xFE separators we
    # don't care about for ASCII).
    codepoint_to_glyph: dict[int, int] = {}
    i = 0
    glyph_idx = 0
    cur = bytearray()
    while i < len(uc_table) and glyph_idx < length:
        b = uc_table[i]
        if b == 0xFF:
            for cp_str in cur.split(b"\xfe"):
                if cp_str:
                    try:
                        cp = cp_str.decode("utf-8")[0]
                        codepoint_to_glyph.setdefault(ord(cp), glyph_idx)
                    except UnicodeDecodeError:
                        pass
            cur = bytearray()
            glyph_idx += 1
        else:
            cur.append(b)
        i += 1

    glyphs: dict[str, list[int]] = {}
    for cp, idx in codepoint_to_glyph.items():
        ch = chr(cp)
        rows_msb = glyph_data[idx * charsize : (idx + 1) * charsize]
        # PSF stores MSB-leftmost; the Verilog font ROM reads LSB-leftmost
        # via `row[x[2:0]]`, so reverse each byte's bit order.
        rows = [int(f"{b:08b}"[::-1], 2) for b in rows_msb]
        glyphs[ch] = rows
    return glyphs


def render_glyphs(chars: list[str]) -> list[list[int]]:
    psf = load_psf_glyphs()
    out = []
    for ch in chars:
        if ch == " ":
            out.append([0] * CHAR_H)
        else:
            if ch not in psf:
                raise SystemExit(f"PSF font has no glyph for {ch!r}")
            out.append(psf[ch])
    return out


def main() -> None:
    chars = collect_chars(MESSAGES)
    assert len(chars) <= 32, f"need 5-bit char indices, have {len(chars)}"

    glyphs = render_glyphs(chars)

    # font_rom: NCHARS chars x 16 rows x 1 byte. Sized to exactly the
    # glyphs we use so the synthesizer doesn't carry dead char slots.
    # Address = (char_idx * 16) + row, computed in HW via concat of the
    # 5-bit ci and 4-bit row when NCHARS == 32, or as a 9-bit add otherwise.
    NCHARS = len(glyphs)
    font_data = []
    for rows in glyphs:
        font_data.extend(rows)
    assert len(font_data) == NCHARS * CHAR_H

    # msg_rom: 3 messages x 16 chars x 5-bit char index. Pack as 8-bit
    # entries indexed by {msg_id[1:0], char_x[3:0]} = 6 bits = 64 bytes.
    char_to_idx = {c: i for i, c in enumerate(chars)}
    msg_data = [0] * (4 * COLS)  # 4 reserved slots, only 3 used
    for mi, msg in enumerate(MESSAGES):
        # Center each message within 16 cols by left-padding with spaces.
        pad = (COLS - len(msg)) // 2
        padded = (" " * pad + msg).ljust(COLS, " ")
        for ci, ch in enumerate(padded):
            msg_data[mi * COLS + ci] = char_to_idx[ch]

    lines = [
        "/*",
        " * Auto-generated by scripts/gen_font_rom.py.",
        " * Character-indexed text rendering: a small font ROM holds one copy",
        " * of each glyph; a per-message char-stream ROM names the columns.",
        " * Three 128x16 text bands are reconstructed at pixel-time.",
        " * SPDX-License-Identifier: Apache-2.0",
        " */",
        "",
        "`default_nettype none",
        "",
        "module bitmap_rom (",
        "    input  wire [6:0]       x0,",
        "    input  wire [3:0]       y0,",
        "    output wire             pixel0,",
        "    input  wire [6:0]       x1,",
        "    input  wire [3:0]       y1,",
        "    output wire             pixel1,",
        "    input  wire [6:0]       x2,",
        "    input  wire [3:0]       y2,",
        "    output wire             pixel2",
        ");",
        "",
        f"  // Font ROM: {NCHARS} glyphs x {CHAR_H} rows = {NCHARS * CHAR_H} bytes.",
        f"  // Declared at the full 5-bit char-index range so {{ci, y}} is a",
        f"  // valid 9-bit address; entries past the last used glyph are",
        f"  // intentionally left uninitialized so the synthesizer treats them",
        f"  // as don't-cares and can prune the dead char slots.",
        f"  reg [7:0] font [0:{32 * CHAR_H - 1}];",
        f"  // Message ROM: 3 messages x {COLS} chars (5-bit char index per cell).",
        f"  reg [4:0] msgs [0:{3 * COLS - 1}];",
        "",
        "  initial begin",
    ]
    for i, v in enumerate(font_data):
        lines.append(f"    font[{i}] = 8'h{v:02x};")
    for mi in range(3):
        for ci in range(COLS):
            v = msg_data[mi * COLS + ci]
            lines.append(f"    msgs[{mi * COLS + ci}] = 5'd{v};")
    lines += [
        "  end",
        "",
        "  // Per-port: lookup char_idx from message stream, then pixel from font.",
        "  wire [4:0] ci0 = msgs[{2'd0, x0[6:3]}];",
        "  wire [4:0] ci1 = msgs[{2'd1, x1[6:3]}];",
        "  wire [4:0] ci2 = msgs[{2'd2, x2[6:3]}];",
        "  wire [7:0] row0 = font[{ci0, y0}];",
        "  wire [7:0] row1 = font[{ci1, y1}];",
        "  wire [7:0] row2 = font[{ci2, y2}];",
        "  assign pixel0 = row0[x0[2:0]];",
        "  assign pixel1 = row1[x1[2:0]];",
        "  assign pixel2 = row2[x2[2:0]];",
        "",
        "endmodule",
        "",
    ]
    Path("src/bitmap_rom.v").write_text("\n".join(lines))
    print(
        f"wrote src/bitmap_rom.v: {len(chars)} unique glyphs from {PSF_PATH}, "
        f"{NCHARS * CHAR_H} font bytes + {3 * COLS} msg cells"
    )

    # Preview
    print("\n=== preview ===")
    for mi, msg in enumerate(MESSAGES):
        pad = (COLS - len(msg)) // 2
        padded = (" " * pad + msg).ljust(COLS, " ")
        print(f"--- {msg!r} (padded: {padded!r}) ---")
        for r in range(CHAR_H):
            line = ""
            for ci in range(COLS):
                idx = char_to_idx[padded[ci]]
                byte = glyphs[idx][r]
                for c in range(CHAR_W):
                    line += "#" if byte & (1 << c) else "."
            print(line)


if __name__ == "__main__":
    main()
