#!/usr/bin/env python3
"""Render the three bouncing-text bands into src/bitmap_rom.v.

Layout (128 px wide, varying heights):
  band 0: 'RISC-V Ottawa'  16 px tall  -> ROM y in [ 0..15]
  band 1: 'Join us!'       16 px tall  -> ROM y in [16..31]
  band 2: 'riscvottawa.ca' 32 px tall  -> ROM y in [32..63]

Total: 64 rows x 16 bytes = 1024 bytes (vs 1536 before).
"""

from __future__ import annotations
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

W = 128
BANDS = [
    ("RISC-V Ottawa", 16),
    ("Join us!", 16),
    ("riscvottawa.ca", 32),
]
FONT_BOLD = "/usr/share/fonts/liberation/LiberationSans-Bold.ttf"
FONT_REG  = "/usr/share/fonts/liberation/LiberationSans-Regular.ttf"


def best_size(font_path: str, text: str, max_w: int, max_h: int) -> int:
    """Largest pt size whose rendered bbox fits in (max_w, max_h)."""
    lo, hi, best = 4, max_h * 2, 4
    while lo <= hi:
        mid = (lo + hi) // 2
        f = ImageFont.truetype(font_path, mid)
        l, t, r, b = f.getbbox(text)
        if (r - l) <= max_w and (b - t) <= max_h:
            best = mid
            lo = mid + 1
        else:
            hi = mid - 1
    return best


def render_band(text: str, height: int) -> list[list[int]]:
    """Return a [height][W] 0/1 pixel grid for text, centered horizontally."""
    # Pick font: bold for short strings, regular for the long URL so
    # 'riscvottawa.ca' still has air at 32 px.
    font_path = FONT_REG if len(text) >= 12 else FONT_BOLD
    pt = best_size(font_path, text, W - 2, height)
    font = ImageFont.truetype(font_path, pt)
    img = Image.new("L", (W, height), 0)
    draw = ImageDraw.Draw(img)
    l, t, r, b = font.getbbox(text)
    tw, th = r - l, b - t
    x = (W - tw) // 2 - l
    y = (height - th) // 2 - t
    draw.text((x, y), text, fill=255, font=font)
    grid = []
    for row in range(height):
        grid.append([1 if img.getpixel((c, row)) >= 128 else 0 for c in range(W)])
    return grid


def main() -> None:
    rows: list[list[int]] = []
    for text, h in BANDS:
        for r in render_band(text, h):
            rows.append(r)
    total_rows = sum(h for _, h in BANDS)
    assert len(rows) == total_rows

    bytes_out: list[int] = []
    for row in rows:
        for byte_idx in range(W // 8):
            v = 0
            for b in range(8):
                if row[byte_idx * 8 + b]:
                    v |= 1 << b
            bytes_out.append(v)

    addr_bits = (len(bytes_out) - 1).bit_length()
    out = Path("src/bitmap_rom.v")
    lines = [
        "/*",
        " * Auto-generated by scripts/gen_bitmap_rom.py.",
        " * Three text bands at varying heights (total 64 rows x 16 bytes = 1024 B):",
        " *   y in [ 0..15] : 'RISC-V Ottawa'",
        " *   y in [16..31] : 'Join us!'",
        " *   y in [32..63] : 'riscvottawa.ca'",
        " * SPDX-License-Identifier: Apache-2.0",
        " */",
        "",
        "`default_nettype none",
        "",
        "module bitmap_rom (",
        "    input  wire [6:0]       x0,",
        "    input  wire [5:0]       y0,",
        "    output wire             pixel0,",
        "    input  wire [6:0]       x1,",
        "    input  wire [5:0]       y1,",
        "    output wire             pixel1,",
        "    input  wire [6:0]       x2,",
        "    input  wire [5:0]       y2,",
        "    output wire             pixel2",
        ");",
        "",
        f"  reg [7:0] mem[0:{len(bytes_out) - 1}];",
        "",
        "  initial begin",
    ]
    for i, v in enumerate(bytes_out):
        lines.append(f"    mem[{i}] = 8'h{v:02x};")
    lines += [
        "  end",
        "",
        f"  wire [{addr_bits - 1}:0] addr0 = {{y0, x0[6:3]}};",
        f"  wire [{addr_bits - 1}:0] addr1 = {{y1, x1[6:3]}};",
        f"  wire [{addr_bits - 1}:0] addr2 = {{y2, x2[6:3]}};",
        "  assign pixel0 = mem[addr0][x0[2:0]];",
        "  assign pixel1 = mem[addr1][x1[2:0]];",
        "  assign pixel2 = mem[addr2][x2[2:0]];",
        "",
        "endmodule",
        "",
    ]
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(bytes_out)} bytes)")


if __name__ == "__main__":
    main()
